name: macos

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby: [ '2.7', '2.6', '2.5' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run test
      run: bundle exec rake
